### ISSUE TITLE
An overview of CircleCI issues

### ISSUE THREAD

**Issue by wehs7661** [wehs7661/ensemble_md#55]
Here is a list of CirclCI issues we have encountered using different settings in `.circleci/config.yml`.

## Using the default virtual machine 
This refers to the case where the `config.yaml` file contains a section like below:
```
jobs:
  test:
    machine:
      - image: default
 
...
```
Currently, the default virtual machine uses Python 3.12, which always triggers the issue mentioned in #52 when installing `ensemble_md`. An example failed build can be found in https://github.com/wehs7661/ensemble_md/commit/b9ba4785c1169da8c5858ede74c9f8cd7c066b60.

## Using Docker images
This refers to the case where `config.yaml` file contains a section like below:
```
jobs:
  test:
    docker:
      - image: cimg/python:<<parameters.python-version>>
    parameters:
      python-version:
        type: string

...
```
Multiple builds based on different Python versions can be launched by the following section:
```
workflows:
  continuous-integration:
    jobs:
      - test:
          name: test-python-3.8
          python-version: "3.8"
      - test:
          name: test-python-3.9
          python-version: "3.9"

...
```
Here are issues we have seen for builds based on different versions.
- Python 3.8: CI builds based on Python 3.8 seem to frequently get stuck when running `test_init` in `test_replica_exchange_EE.py`. An example failed build can be found in 63cece8. 
- Python 3.9: CI builds based on Python 3,9 seem to frequently get stuck when running `test_combine_df_adjacent ` in `test_analyze_free_energy.py`. An example failed build can be found in fc5c093.
- Python 3.10 and Python 3.11: CI builds based on 3.10 and 3.11 work most of the time, with only exceptions being failures from MPI tests as mentioned in #44. An example failed build can be found in 154c2b4 (for both versions). 
- Python 3.12: CI builds based on Python 3.12 trigger issue #52 as mentioned above. 

## Temporary workaround
These are likely issues stemming from CircleCI itself rather than our package. For now, we remove tests based on Python versions 3.8, 3.9, and 3.12 and only preserve those based on Python 3.10 and 3.11. In addition, we remove MPI tests. We will revisit these CI issues when they become a bottleneck for the development of the package.
